In [10]:
#Importing Libraries 
import numpy as np
import pandas as pd
#Importing Dataset
dataset = pd.read_csv(r"C:\Aaryan\PROJECT\dataset.csv")

In [11]:
dataset

   Gender Eye Strain Anti-Glare Filter   Hours  cvs
0       m       high               yes    high  yes
1       m     medium               yes    high  yes
2       m        low                no  medium  yes
3       f       high                no     low   no
4       m       high               yes    high  yes
5       f     medium               yes    high   no
6       m     medium               yes    high  yes
7       m       high                no  medium   no
8       f       high               yes    high  yes
9       f     medium               yes  medium  yes
10      f        low                no     low   no
11      f       high               yes  medium   no
12      f       high                no    high  yes
13      f     medium               yes     low   no
14      m        low                no  medium   no
15      m        low               yes  medium  yes
16      m     medium                no  medium  yes
17      m     medium               yes    high  yes
18      f        low               yes  medium  yes
19      f        low               yes  medium   no
20      m     medium               yes    high  yes
21      f     medium               yes  medium  yes
22      m        low                no     low   no
23      m     medium               yes  medium   no
24      m     medium               yes     low   no
25      f       high               yes  medium  yes
26      f       high                no     low   no
27      f       high                no     low   no
28      f     medium                no  medium   no
29      m       high                no     low   no

In [12]:
#Assigning numbers to word input in Gender column for betterment analysis.
dataset = dataset.replace(to_replace='m', value=1)
dataset = dataset.replace(to_replace='f', value=2)

In [13]:
#Assigning numbers to word input in Eye Strain column for betterment analysis.
dataset = dataset.replace(to_replace='high', value=2)
dataset = dataset.replace(to_replace='medium', value=1)
dataset = dataset.replace(to_replace='low', value=0)

In [14]:
#Assigning numbers to word input in Anti-Glare Filter column for betterment analysis.
dataset = dataset.replace(to_replace='yes', value=0)
dataset = dataset.replace(to_replace='no', value=1)
dataset

    Gender  Eye Strain  Anti-Glare Filter  Hours  cvs
0        1           2                  0      2    0
1        1           1                  0      2    0
2        1           0                  1      1    0
3        2           2                  1      0    1
4        1           2                  0      2    0
5        2           1                  0      2    1
6        1           1                  0      2    0
7        1           2                  1      1    1
8        2           2                  0      2    0
9        2           1                  0      1    0
10       2           0                  1      0    1
11       2           2                  0      1    1
12       2           2                  1      2    0
13       2           1                  0      0    1
14       1           0                  1      1    1
15       1           0                  0      1    0
16       1           1                  1      1    0
17       1           1                  0      2    0
18       2           0                  0      1    0
19       2           0                  0      1    1
20       1           1                  0      2    0
21       2           1                  0      1    0
22       1           0                  1      0    1
23       1           1                  0      1    1
24       1           1                  0      0    1
25       2           2                  0      1    0
26       2           2                  1      0    1
27       2           2                  1      0    1
28       2           1                  1      1    1
29       1           2                  1      0    1

In [15]:
from sklearn.model_selection import train_test_split
X = dataset.drop(["cvs"], axis=1)
y = dataset["cvs"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [17]:
#Applying Logistic Regression to the dataset
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train,y_train)

LogisticRegression()

In [19]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0], dtype=int64)

In [20]:
y_test

8     0
13    1
9     0
6     0
18    0
12    0
3     1
4     0
0     0
17    0
Name: cvs, dtype: int64

In [21]:
#Finding the accuracy of the model
print("Accuracy : {}".format(clf.score(X_test,y_test)))

Accuracy : 0.7

In [22]:
#Applying Gaussian Naive Bayes to our dataset
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)
#Predicting the output
y_pred=nb.predict(X_test)

In [23]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0], dtype=int64)

In [24]:
y_test

8     0
13    1
9     0
6     0
18    0
12    0
3     1
4     0
0     0
17    0
Name: cvs, dtype: int64

In [25]:
#Finding the accuracy of the model
print("Accuracy : {}".format(nb.score(X_test,y_test)))

Accuracy : 0.7